### ISSUE TITLE
Deploy in Sagemaker notebook instead of EC2

### ISSUE THREAD

**Issue by hughandersen** [aws-samples/reinvent2020-aim404-productionize-r-using-amazon-sagemaker#1]
@michaelhsieh42 This is a great example, but I'm learning to use AWS and I'm trying to run it in a Sagemaker notebook and have some problems, so maybe not exactly an issue.

1. In file `sagemaker_training.ipynb` the line of code `system(sprintf('./build_and_push_docker.sh %s %s', container, tag))` doesn't deploy the container.
2. In the line of code ``rds_file = '/home/ubuntu/reinvent2020-aim404-productionize-r-using-amazon-sagemaker/tourism_tsbl.rds`` I am not sure where to find the rds file and if a path is required

**Comment by michaelhsieh42** [comment]
Thanks for your feedback. Note that this example is developed and tested in an environment provisioned by the accompanying cloudformation template. So question 1 may be impacted if you leave the provisioned environment.

Are you running in a [SageMaker Notebook Instance](https://docs.aws.amazon.com/sagemaker/latest/dg/nbi.html) or in a [SageMaker Studio](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-ui.html)? What kernel do you use? 

As for 2, the variable `rds_file` holds a path/filename in order to save `tourism` dataset from `tsibble` package into an RDS file. So the rds file won't exist until [the next line](https://github.com/aws-samples/reinvent2020-aim404-productionize-r-using-amazon-sagemaker/blob/main/sagemaker_training.r#L30) `saveRDS(tourism, file=rds_file)` is executed. Also the filepath assumes the underlying OS is ubuntu and has a home directory `/home/ubuntu/`. This is not the case in neither SageMaker Notebook Instance nor SageMaker Studio. You need to modify the path accordingly.

**Comment by hughandersen** [comment]
Thanks for replying @michaelhsieh42 .
1. I am running your code in Sagemaker Stuidio using an R kernel. Can the container be created using similar code?
2. I'll change the path and I can see that the file `tourism` is created in `fable_demo.ipynb`

**Comment by michaelhsieh42** [comment]
Hi,
This solution does not supported running in SageMaker Studio Notebook. Studio Notebook does not have `docker` to build a container image, which is what we used in [build_and_push_docker.sh](https://github.com/aws-samples/reinvent2020-aim404-productionize-r-using-amazon-sagemaker/blob/main/build_and_push_docker.sh#L11). 

The current work around is to use a pip installable package `sagemaker-studio-image-build` as shown in this blog:
https://aws.amazon.com/blogs/machine-learning/using-the-amazon-sagemaker-studio-image-build-cli-to-build-container-images-from-your-studio-notebooks/ to build the container.
